import type { ContatoDTO } from "./ContatoDTO";
import type { EnderecoDTO, VitimaDTO, VitimaFotoDTO } from "./EnderecoDTO";
import type { EntrevistaComportamentalDTO } from "./EntrevistaComportamentalDTO";
import type { EntrevistaDesaparecimentoDTO } from "./EntrevistaDesaparecimentoDTO";
import type { RedeSocialDTO } from "./RedeSocialDTO";

export interface DelegaciaDigitalDTO {
  protocolo?: string;
  numAip?: string;
  numIp?: string;
  enderecos: EnderecoDTO[];
  vitima: VitimaDTO;
  vitimaFotos?: VitimaFotoDTO[];
  unidadeId?: number;
  usuarioCadastroId?: number;
  boNumero?: string;
  origemBO?: string;
  codBO?: number;
  dataHoraFato?: string;
  altura?: string;
  compleicao?: string;
  cabeloCor?: string;
  cabeloTipo?: string;
  olhoTipo?: string;
  olhoCor?: string;
  fratura?: string;
  placaMetalica?: string;
  tatuagem?: string;
  cicatriz?: string;
  arcadaDentaria?: string;
  aparelhoDentario?: boolean;
  defeitoFisico?: string;
  deficienciaFisica?: string;
  deficienciaMental?: boolean;
  deficienciaMentalCuratela?: boolean;
  deficienciaMentalLaudo?: boolean;
  deficienciaMentalInterdicao?: boolean;
  doencaTransmissivelIncuravel?: string;
  gravidez?: boolean;
  cegueira?: boolean;
  faccao?: boolean;
  faccaoNome?: string;
  grupoSanguineo?: string;
  fatorRh?: string;
  contatos?: ContatoDTO[];
  entrevistaComportamental?: EntrevistaComportamentalDTO;
  entrevistaDesaparecimento?: EntrevistaDesaparecimentoDTO;
  grauParentescoComunicante?: string;
  grauParentescoLocalizacao?: string;
  telefoneLocalizacao?: string;
  condicaoLocalizacao?: string;
  encontradoVivo?: boolean;
  sigiloso?: boolean;
  grauParentescoPessoaTermo?: string;
  informacaoMorte?: boolean;
  informacaoMorteBoNumero?: string;
  nomeUsuarioCadastro?: string;
  cargoUsuarioCadastro?: string;
  comunicante?: VitimaDTO;
  redesSociaisVitima?: RedeSocialDTO[];
}